### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by jeylites** [MacWyznawca/homebridge-mqtt-switch-tasmota#16]
I'm trying to test this out but I'm getting the following error. What could it be?

```
j-MBP:~ j$ homebridge
[10/11/2017, 12:01:14 AM] Loaded plugin: homebridge-http-garagedoorcontroller
[10/11/2017, 12:01:14 AM] Registering accessory 'homebridge-http-garagedoorcontroller.HttpGarageDoorController'
[10/11/2017, 12:01:14 AM] ---
[10/11/2017, 12:01:14 AM] Loaded plugin: homebridge-mqtt-switch-tasmota
[10/11/2017, 12:01:14 AM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[10/11/2017, 12:01:14 AM] ---
[10/11/2017, 12:01:15 AM] Loaded plugin: homebridge-people
[10/11/2017, 12:01:15 AM] Registering platform 'homebridge-people.People'
[10/11/2017, 12:01:15 AM] Registering accessory 'homebridge-people.PeopleAccessory'
[10/11/2017, 12:01:15 AM] Registering accessory 'homebridge-people.PeopleAllAccessory'
[10/11/2017, 12:01:15 AM] ---
[10/11/2017, 12:01:15 AM] Loaded config.json with 1 accessories and 0 platforms.
[10/11/2017, 12:01:15 AM] ---
[10/11/2017, 12:01:15 AM] Loading 0 platforms...
[10/11/2017, 12:01:15 AM] Loading 1 accessories...
[10/11/2017, 12:01:15 AM] [sonoff] Initializing mqtt-switch-tasmota accessory...
[10/11/2017, 12:01:15 AM] [sonoff] Nazwa do RESULT  POWER
/usr/local/lib/node_modules/homebridge-mqtt-switch-tasmota/node_modules/mqtt/lib/connect/index.js:62
    opts.protocol = opts.protocol.replace(/\:$/, '');
                                 ^

TypeError: Cannot read property 'replace' of null
    at Object.connect (/usr/local/lib/node_modules/homebridge-mqtt-switch-tasmota/node_modules/mqtt/lib/connect/index.js:62:34)
    at new MqttSwitchTasmotaAccessory (/usr/local/lib/node_modules/homebridge-mqtt-switch-tasmota/index.js:94:21)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:265:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Config File** 

```
{
   "bridge":{
      "name":"Homebridge",
      "username":"83:45:35:66:EE:9A",
      "port":51829,
      "pin":"031-45-407"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",

    "platforms": [],

    "accessories": [
        {
    		"accessory": "mqtt-switch-tasmota",

    		"name": "sonoff",

    		"url": "192.168.1.10",

    		"topics": {
    			"statusGet": "stat/sonoff/POWER",
    			"statusSet": "cmnd/sonoff/POWER"
    		}
    	}
    ]
    }
```

**Comment by jeylites** [comment]
Never mind the mistake was the url... it needs to be the following formate eg: mqtt://192.168.1.10

**Comment by seekerPL** [comment]
Hi @MacWyznawca , can you tell me what I'm doing wrong?

In my config I added my TV plus 2 Sonoff basic.

[2018-9-20 13:30:49] Loaded config.json with 3 accessories and 0 platforms.
[2018-9-20 13:30:49] ---
[2018-9-20 13:30:49] Loaded plugin: homebridge-mqtt-switch-tasmota
[2018-9-20 13:30:49] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[2018-9-20 13:30:49] ---
[2018-9-20 13:30:49] Loaded plugin: homebridge-panasonictv
[2018-9-20 13:30:49] Registering accessory 'homebridge-panasonictv.TV'
[2018-9-20 13:30:49] ---
[2018-9-20 13:30:50] Loaded plugin: homebridge-sonoff
[2018-9-20 13:30:50] Registering platform 'homebridge-sonoff.Sonoff'
[2018-9-20 13:30:50] ---
[2018-9-20 13:30:50] Loading 0 platforms...
[2018-9-20 13:30:50] Loading 3 accessories...
[2018-9-20 13:30:50] [Sonoff01] Initializing mqtt-switch-tasmota accessory...
[2018-9-20 13:30:50] [Sonoff01] Nazwa do RESULT  POWER
[2018-9-20 13:30:50] [Sonoff02] Initializing mqtt-switch-tasmota accessory...
[2018-9-20 13:30:50] [Sonoff02] Nazwa do RESULT  POWER
[2018-9-20 13:30:50] [TV] Initializing TV accessory...
Load homebridge-sonoff.Sonoff
/usr/lib/node_modules/homebridge-sonoff/index.js:16
  platform.config.devices = platform.config.devices || [];
                                            ^

TypeError: Cannot read property 'devices' of null
    at new Sonoff (/usr/lib/node_modules/homebridge-sonoff/index.js:16:45)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:346:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

[homebridge_seeker_json.txt](https://github.com/MacWyznawca/homebridge-mqtt-switch-tasmota/files/2401069/homebridge_seeker_json.txt)
