### ISSUE TITLE
Error: ReferenceError: data is not defined

### ISSUE THREAD

**Issue by elfnino** [MacWyznawca/homebridge-mqtt-switch-tasmota#4]
5/3/2017, 9:54:40 PM] [prvePOW] Initializing mqtt-power-consumption-log-tasmota accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â 031-45-154 â
    ââââââââââââââ

[5/3/2017, 9:54:40 PM] Homebridge is running on port 51826.
[5/3/2017, 9:54:40 PM] [prvePOW] Nothing to change _hourly
[5/3/2017, 9:54:40 PM] [prvePOW] Nothing to change _daily
[5/3/2017, 9:54:40 PM] [prvePOW] Nothing to change _period
/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398
                        data = null;
                             ^

ReferenceError: data is not defined
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/index.js:398:9)
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:194:7)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:821:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:286:12)
    at process (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:242:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/mqtt/lib/client.js:252:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-mqtt-power-consumption-log-tasmota/node_modules/readable-stream/lib/_stream_writable.js:264:11)

**Comment by elfnino** [comment]
this was related to Sonoff POW plugin
